# Set the prefix to ctrl-a
set-option -g   prefix C-a
bind-key C-a    send-prefix

unbind r
bind-key r source-file ~/.tmux.conf

set-option -g history-limit 100000
set-option -g status-interval 1
set-option -g monitor-silence 30

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

set-window-option -g mode-keys vi

bind | split-window -h
bind - split-window -v

# Hide and unhide panes
bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s $.0

set-option -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text "#W#F"
set -g @catppuccin_window_current_text "#W#F"
set -g status-right "#H #{E:@catppuccin_status_application} #[fg=#{@thm_crust},bg=#{@thm_teal}] %H:%M "
set -g status-left ""

set -g status-right-length 100
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'
set-option -g status-interval 1


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
