# Set the prefix to ctrl-a
set-option -g   prefix C-a
bind-key C-a    send-prefix

bind-key -n F1 copy-mode

unbind r
bind-key r source-file ~/.tmux.conf

set-option -g default-command "exec $SHELL -l"

set-option -g history-limit 100000
set-option -g status-interval 1
set-option -g monitor-silence 30

# act like vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# unbind ctrl-l to allow shell clear screen
unbind -n C-l

bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5

set-window-option -g mode-keys vi

bind | split-window -h
bind - split-window -v

# Hide and unhide panes
bind-key ! break-pane -d -n _hidden_pane
bind-key @ join-pane -s $.0

set-option -g default-terminal "screen-256color"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'

set -g status-right-length 100


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
