#!/bin/bash
# vi: ft=sh

ensure_pew() {
    if ! command -v pew >/dev/null 2>&1; then
        pipx install pew
    else
        echo "pew is already installed"
    fi
}

ensure_zsh() {
    if [[ $SHELL != *zsh ]]; then
        echo "Changing shell to ZSH"
        chsh -s /usr/bin/zsh
    else
        echo "Shell is already ZSH"
    fi
}

if [ -f /etc/debian_version ]; then
    echo "Detected debian-based distro";

    sudo apt update && sudo apt install -y \
        tmux \
        neovim \
        zsh \
        pipx \
        luarocks \

    ensure_pew
    ensure_zsh
fi

if [ -f /etc/arch-release ]; then
    echo "Detected arch-based distro";

    sudo pacman -Syu --noconfirm \
        autoconf \
        automake \
        gcc \
        keychain \
        luarocks \
        neovim \
        nodejs \
        npm \
        python-pipx \
        ripgrep \
        rustup \
        shellcheck \
        starship \
        tmux \
        unzip \
        uv \
        zsh \

    ensure_pew
    ensure_zsh
fi

if ! command -v starship >/dev/null 2>&1; then
    curl -sS https://starship.rs/install.sh | sh
else
    echo "starship is already installed"
fi

[[ ! -e ~/.tmux/plugins/tpm ]] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

WSLPATH=$(command -v wslpath)
if [[ "$WSLPATH" ]]; then
    echo "Detected WSL"
    USERPROFILE=$($WSLPATH "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null | tr -d '\r')")
    if [ ! -e "$USERPROFILE/.wezterm.lua" ]; then
        ln -s ~/.config/wezterm/wezterm.lua "$USERPROFILE/.wezterm.lua"
    else
        echo "wezterm.lua already exists in $USERPROFILE"
    fi
fi
