#!/bin/bash

# vi: ft=sh
if [ -f /etc/debian_version ]; then
    echo "Detected debian-based distro";

    sudo apt update && sudo apt install -y \
        tmux \
        neovim \
        zsh \
        pipx \
        luarocks \

    if ! command -v pew >/dev/null 2>&1; then
        pipx install pew
    else
        echo "pew is already installed"
    fi

    if [[ $0 != *zsh ]]; then
        echo "Changing shell to ZSH"
        chsh -s /usr/bin/zsh
    else
        echo "Shell is already ZSH"
    fi
fi

if ! command -v starship >/dev/null 2>&1; then
    curl -sS https://starship.rs/install.sh | sh
else
    echo "starship is already installed"
fi

[[ ! -e ~/.tmux/plugins/tpm ]] && git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

WSLPATH=$(command -v wslpath)
if [[ "$WSLPATH" ]]; then
    echo "Detected WSL"
    USERPROFILE=$($WSLPATH "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null | tr -d '\r')")
    if [ ! -e $USERPROFILE/.wezterm.lua ]; then
        ln -s ~/.config/wezterm/wezterm.lua $USERPROFILE/.wezterm.lua
    else
        echo "wezterm.lua already exists in $USERPROFILE"
    fi
fi
