#!/bin/bash
# vi: ft=sh

ensure_pew() {
    if ! command -v pew >/dev/null 2>&1; then
        pipx install pew
    else
        echo "pew is already installed"
    fi
}

ensure_zsh() {
    if [[ $SHELL != *zsh ]]; then
        echo "Changing shell to ZSH"
        chsh -s /usr/bin/zsh
    else
        echo "Shell is already ZSH"
    fi
}

if [ -f /etc/debian_version ]; then
    echo "Detected debian-based distro";

    sudo apt update && sudo apt install -y \
        curl \
        gcc \
        fzf \
        keychain \
        luarocks \
        pipx \
        ripgrep \
        tmux \
        zsh

    if grep -q "^ID=ubuntu" /etc/os-release; then
        sudo snap install --classic nvim docker
        if ! command -v node; then
            export KEEP_ZSHRC=yes
            cd /tmp && \
                curl -fsSL https://deb.nodesource.com/setup_23.x -o nodesource_setup.sh && \
                sudo -E bash nodesource_setup.sh && \
                sudo apt-get install -y nodejs
        else
            echo "Node.js is already installed."
    fi
    fi

    ensure_pew
    ensure_zsh
fi

if [ -f /etc/arch-release ]; then
    echo "Detected arch-based distro";

    sudo pacman -Syu --noconfirm \
        autoconf \
        automake \
        fzf \
        gcc \
        keychain \
        luarocks \
        man-db \
        man-pages \
        neovim \
        nodejs \
        npm \
        python-pipx \
        ripgrep \
        rustup \
        shellcheck \
        starship \
        tmux \
        unzip \
        uv \
        zsh \

    ensure_pew
    ensure_zsh
fi

if [[ -e /home/lkollar/.oh-my-zsh ]]; then
    echo "oh-my-zsh already installed"
else
    echo "Installing oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc
fi

if command -v pygmentize >/dev/null 2>&1; then
    echo "Pygments already installed"
else
    echo "Installing Pygments"
    pipx install pygments
    pipx inject pygments catppuccin[pygments]
fi

if [[ ! -e ~/.tmux/plugins/tpm ]]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    cd ~/.tmux/plugins/tpm/scripts && ./install_plugins.sh
fi

WSLPATH=$(command -v wslpath)
if [[ "$WSLPATH" ]]; then
    echo "Detected WSL"
    USERPROFILE=$($WSLPATH "$(cmd.exe /c "echo %USERPROFILE%" 2>/dev/null | tr -d '\r')")
    if [ ! -e "$USERPROFILE/.wezterm.lua" ]; then
        ln -s ~/.config/wezterm/wezterm.lua "$USERPROFILE/.wezterm.lua"
    else
        echo "wezterm.lua already exists in $USERPROFILE"
    fi
fi
